package penaltyleague.view;

import javax.swing.Timer;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;

public class ShotRoundView implements ActionListener {

    private int selectionPhase;
    protected static final int DIRECTION_SELECTION_PHASE = 1;
    protected static final int HEIGHT_SELECTION_PHASE = 2;
    protected static final int POWER_SELECTION_PHASE = 3;
    protected static final int SELECTIONS_DONE_PHASE = 4;

    private GamePanel gamePanel;

    private BufferedImage directionSelectorImage;
    private BufferedImage heightSelectorImage;
    private BufferedImage powerBarImage;
    private BufferedImage powerSelectorImage;

    private int directionSelectorWidth;
    private int directionSelectorHeight;
    private int xCoordDirectionSelector;
    private int yCoordDirectionSelector;

    private int heightSelectorDimension;
    private int yCoordHeightSelector;

    private int powerBarWidth;
    private int powerBarHeight;
    private int xCoordPowerBar;
    private int yCoordPowerBar;

    private int powerSelectorWidth;
    private int powerSelectorHeight;
    private int yCoordPowerSelector;

    private int directionSelected;
    private int heightSelected;
    private int powerSelected;

    private int directionSelectorShift; //how much each event generated by the timer moves the selector
    private int heightSelectorShift;
    private int powerSelectorShift;
    private boolean directionSelectorMovingToRight;
    private boolean heightSelectorMovingDown;
    private boolean powerSelectorMovingDown;

    private int rightBorderDirection;
    private int leftBorderDirection;
    private int topBorderHeight;
    private int downBorderHeight;
    private int topBorderPower;
    private int downBorderPower;

    private boolean powerMalus;

    private boolean goal;
    private BufferedImage goalSign;
    private BufferedImage missedSign;
    private boolean signVisible;

    private Timer timer;
    private static final int TIMER_DELAY = 10;
    private static final int TIMER_LAG = 6; //the real execution of the timer delay is not 10, but about 16
    private static final int EVENTS_BEFORE_RESTART = 200;
    private int resetEventsCounter;
    private boolean isFirstEventSelectionsDonePhase;

    public ShotRoundView(GamePanel gamePanel){
        this.selectionPhase = DIRECTION_SELECTION_PHASE;
        this.gamePanel = gamePanel;
        loadImages();
        this.timer = new Timer(TIMER_DELAY, this);
        this.resetEventsCounter = 0;
        this.isFirstEventSelectionsDonePhase = true;

        directionSelectorMovingToRight = true;
        heightSelectorMovingDown = true;
        powerSelectorMovingDown = true;

        powerMalus = false;
        signVisible = false;
        goal = false;
    }

    private void loadImages(){
        this.directionSelectorImage = null;
        this.heightSelectorImage = null;
        this.powerBarImage = null;
        this.powerSelectorImage = null;
        this.goalSign = null;
        this.missedSign = null;
        try{
            this.directionSelectorImage = ResourceManager.loadImage("directionSelector.png");
            this.heightSelectorImage = ResourceManager.loadImage("heightSelector.png");
            this.powerBarImage = ResourceManager.loadImage("powerBar.png");
            this.powerSelectorImage = ResourceManager.loadImage("powerSelector.png");
            this.goalSign = ResourceManager.loadImage("goalSign.png");
            this.missedSign = ResourceManager.loadImage("missedSign.png");
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }

    protected void initSelectors(Ball ball){
        directionSelectorWidth = (int) (15 * gamePanel.getView().getUnitOfMeasureScreen());
        directionSelectorHeight = (int) (gamePanel.getGoalHeight() + 150 * gamePanel.getView().getUnitOfMeasureScreen());
        xCoordDirectionSelector = (int) (gamePanel.getLeftPostCenterCoord() - 75 * gamePanel.getView().getUnitOfMeasureScreen());
        yCoordDirectionSelector = (int) (gamePanel.getCrossbarCenterCoord() - 75 * gamePanel.getView().getUnitOfMeasureScreen());

        heightSelectorDimension = ball.getBallDimension();
        yCoordHeightSelector = (int) (gamePanel.getCrossbarCenterCoord() - heightSelectorDimension/2
                        - 75 * gamePanel.getView().getUnitOfMeasureScreen());

        powerBarWidth = (int) (75 * gamePanel.getView().getUnitOfMeasureScreen());
        powerBarHeight = powerBarWidth * 4;
        xCoordPowerBar = gamePanel.getWidth() * 4/5;
        yCoordPowerBar = gamePanel.getHeight() * 2/3;

        powerSelectorWidth = (int) (75 * gamePanel.getView().getUnitOfMeasureScreen());
        powerSelectorHeight = directionSelectorWidth * 3/2;
        yCoordPowerSelector = yCoordPowerBar;

        rightBorderDirection = (int) (gamePanel.getRightPostCenterCoord() + 75 * gamePanel.getView().getUnitOfMeasureScreen());
        leftBorderDirection = (int) (gamePanel.getLeftPostCenterCoord() - 75 * gamePanel.getView().getUnitOfMeasureScreen());

        downBorderHeight = yCoordDirectionSelector + directionSelectorHeight - heightSelectorDimension/2;
        topBorderHeight = yCoordDirectionSelector - heightSelectorDimension/2;

        downBorderPower = yCoordPowerBar + powerBarHeight - powerSelectorHeight;
        topBorderPower = yCoordPowerBar;
    }

    protected int getSelectionPhase(){
        return selectionPhase;
    }

    protected void resetSelectionPhase(){
        selectionPhase = DIRECTION_SELECTION_PHASE;
        powerMalus = false;
    }

    protected void increaseSelectionPhase(){
        selectionPhase++;
    }

    protected void setDirection(){
        directionSelected = xCoordDirectionSelector + directionSelectorWidth/2;
    }

    protected void setHeight(){
        heightSelected = yCoordHeightSelector + heightSelectorDimension/2;

        // selecting below the goal line height is like hitting the ground, so the power is minimized
        if(heightSelected > gamePanel.getCrossbarCenterCoord() + gamePanel.getGoalHeight()){
            heightSelected = gamePanel.getCrossbarCenterCoord() + gamePanel.getGoalHeight();
            powerMalus = true;
        }
    }

    protected void setPower(){
        if(powerMalus){
            powerSelected = 0;
        }
        else{
            int powerRelativeToPowerBarHeight = (yCoordPowerBar + powerBarHeight) - (yCoordPowerSelector + powerSelectorHeight/2);
            powerSelected = (int)(powerRelativeToPowerBarHeight*100.0/powerBarHeight);
        }
    }

    protected int getDirection(){
        return directionSelected;
    }

    protected int getHeight(){
        return heightSelected;
    }

    protected int getPower(){
        return powerSelected;
    }

    protected void drawSelectors(Graphics2D g2d){
        if(selectionPhase == DIRECTION_SELECTION_PHASE){
            g2d.drawImage(directionSelectorImage, xCoordDirectionSelector, yCoordDirectionSelector,
                    directionSelectorWidth, directionSelectorHeight, null);
        }

        if(selectionPhase == HEIGHT_SELECTION_PHASE){
            g2d.drawImage(heightSelectorImage, directionSelected - heightSelectorDimension/2,
                    yCoordHeightSelector, heightSelectorDimension, heightSelectorDimension, null);
        }
        else if(selectionPhase == POWER_SELECTION_PHASE){
            g2d.drawImage(powerBarImage, xCoordPowerBar, yCoordPowerBar, powerBarWidth, powerBarHeight, null);

            g2d.drawImage(powerSelectorImage, xCoordPowerBar, yCoordPowerSelector,
                    powerSelectorWidth, powerSelectorHeight, null);
        }
    }

    protected boolean isSignVisible(){
        return signVisible;
    }

    protected boolean isGoal(){
        return goal;
    }

    protected void drawSign(Graphics2D g2d){
        int signWidth = gamePanel.getWidth()/3;
        int signHeight = signWidth * goalSign.getHeight()/goalSign.getWidth();
        if(goal){
            g2d.drawImage(goalSign, gamePanel.getWidth()/2 - signWidth/2, gamePanel.getHeight()/2 - signHeight/2,
                    signWidth, signHeight, null);
        }
        else {
            g2d.drawImage(missedSign, gamePanel.getWidth()/2 - signWidth/2, gamePanel.getHeight()/2 - signHeight/2,
                    signWidth, signHeight, null);
        }
    }

    protected void start(){
        int opponentTeamIndex = gamePanel.getView().getLogic().getOpponentTeamIndex();

        directionSelectorShift = (int) ((10 + 2*(gamePanel.getView().getTeams().getTeamRating(opponentTeamIndex)-1))
                        * gamePanel.getView().getUnitOfMeasureScreen());
        heightSelectorShift = (int) ((8 + 2*(gamePanel.getView().getTeams().getTeamRating(opponentTeamIndex)-1))
                        * gamePanel.getView().getUnitOfMeasureScreen());
        powerSelectorShift = (int) ((8 + gamePanel.getView().getTeams().getTeamRating(opponentTeamIndex)-1)
                        * gamePanel.getView().getUnitOfMeasureScreen());

        timer.start();
    }

    protected void stop(){
        timer.stop();
        resetEventsCounter = 0;
        isFirstEventSelectionsDonePhase = true;
        signVisible = false;
        goal = false;
    }

    private void handleActionPerformedDirectionSelection(){
        if(directionSelectorMovingToRight){
            if((xCoordDirectionSelector + directionSelectorShift) <= rightBorderDirection){
                xCoordDirectionSelector += directionSelectorShift;
            }
            else{
                xCoordDirectionSelector = rightBorderDirection;
                directionSelectorMovingToRight = false;
            }
        }
        else{
            if((xCoordDirectionSelector - directionSelectorShift) >= leftBorderDirection){
                xCoordDirectionSelector -= directionSelectorShift;
            }
            else{
                xCoordDirectionSelector = leftBorderDirection;
                directionSelectorMovingToRight = true;
            }
        }

        gamePanel.repaint();
    }

    private void handleActionPerformedHeightSelection(){
        if(heightSelectorMovingDown){
            if((yCoordHeightSelector + heightSelectorShift) <= downBorderHeight){
                yCoordHeightSelector += heightSelectorShift;
            }
            else{
                yCoordHeightSelector = downBorderHeight;
                heightSelectorMovingDown = false;
            }
        }
        else{
            if((yCoordHeightSelector - heightSelectorShift) >= topBorderHeight){
                yCoordHeightSelector -= heightSelectorShift;
            }
            else{
                yCoordHeightSelector = topBorderHeight;
                heightSelectorMovingDown = true;
            }
        }

        gamePanel.repaint();
    }

    private void handleActionPerformedPowerSelection(){
        if(powerSelectorMovingDown){
            if((yCoordPowerSelector + powerSelectorShift) <= downBorderPower){
                yCoordPowerSelector += powerSelectorShift;
            }
            else{
                yCoordPowerSelector = downBorderPower;
                powerSelectorMovingDown = false;
            }
        }
        else{
            if((yCoordPowerSelector - powerSelectorShift) >= topBorderPower){
                yCoordPowerSelector -= powerSelectorShift;
            }
            else{
                yCoordPowerSelector = topBorderPower;
                powerSelectorMovingDown = true;
            }
        }

        gamePanel.repaint();
    }

    private void endOfRound(){
        this.gamePanel.getShooterAnimation().resetStartFrame();
        gamePanel.getBall().resetStartBall();
        this.resetSelectionPhase();
        this.stop();
        this.gamePanel.getGoalkeeperAnimation().stop();
        gamePanel.resetNet();
        if(gamePanel.getView().getLogic().checkUserWin()){
            gamePanel.getView().getLogic().increaseTournamentPhase();
            gamePanel.getView().getMainGUI().changeToTournamentBracketPanel();
            gamePanel.reset();
        }
        else if(gamePanel.getView().getLogic().checkOpponentWin()){
            gamePanel.getView().getLogic().setGameOverPhase();
            gamePanel.getView().getMainGUI().changeToTournamentBracketPanel();
            gamePanel.reset();
        }
        else{
            this.gamePanel.getView().getLogic().changeRound();
            this.gamePanel.getShooterAnimation().start();
        }

        gamePanel.repaint();
    }

    private void handleActionPerformedSelectionsDone(){
        if(isFirstEventSelectionsDonePhase){
            int regionSaveAttempt = gamePanel.getView().getLogic().generateRegionSaveAttempt(
                    getDirection(), getHeight(), getPower());

            goal = gamePanel.getView().getLogic().isGoal(getDirection(), getHeight(), getPower(), regionSaveAttempt);

            isFirstEventSelectionsDonePhase = false;
        }

        if(gamePanel.getBall().isShotDone()){
            if(resetEventsCounter < EVENTS_BEFORE_RESTART) {

                if(resetEventsCounter == 0){
                    if(isGoal()){
                        gamePanel.getView().getSound().playNetSound();
                        gamePanel.getView().getSound().playCelebrationSound();
                    }
                    else{
                        gamePanel.getView().getSound().playDelusionSound();
                    }
                    gamePanel.getView().getLogic().updateUserScoreboard(goal);
                    signVisible = true;
                    gamePanel.repaint();
                }

                if(isGoal() && resetEventsCounter % (SaveRoundView.TIMER_DELAY / (TIMER_DELAY + TIMER_LAG)) == 0)
                    gamePanel.moveNet();

                resetEventsCounter++;

            }
            else{
                endOfRound();
            }
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(selectionPhase == DIRECTION_SELECTION_PHASE){
            handleActionPerformedDirectionSelection();
        }
        else if(selectionPhase == HEIGHT_SELECTION_PHASE){
            handleActionPerformedHeightSelection();
        }
        else if(selectionPhase == POWER_SELECTION_PHASE){
            handleActionPerformedPowerSelection();
        }
        else if(selectionPhase == SELECTIONS_DONE_PHASE){
            handleActionPerformedSelectionsDone();
        }
    }
}
